# Generated by Django 3.1.7 on 2021-04-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
    ]
