# Generated by Django 3.1.7 on 2021-04-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_onlineapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineapplication',
            name='board1',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='month_and_year_of_passing1',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='name_of_institution1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='percentage_of_marks1',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='reg_no1',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
