# Generated by Django 3.1.2 on 2020-11-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_new_brochure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=None, max_length=50)),
                ('description', models.TextField(default=None)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, default=None, upload_to='news')),
                ('brochure', models.ImageField(blank=True, default=None, null=True, upload_to='brochure')),
            ],
        ),
    ]
