# Generated by Django 3.1.2 on 2020-11-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='events'),
        ),
    ]
