# Generated by Django 3.1.2 on 2020-11-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_auto_20201119_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
