# Generated by Django 3.1.7 on 2021-04-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_auto_20210404_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineapplication',
            name='has_enquired',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
