# Generated by Django 3.1.7 on 2021-04-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_auto_20210404_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineapplication',
            name='current_address_line2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='current_city',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='currrent_address_line1',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='has_enquired',
            field=models.BooleanField(default='No', null=True),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='permanent_address_line1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='permanent_address_line2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='permanent_city',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
