# Generated by Django 3.1.2 on 2020-11-21 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_auto_20201119_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=50)),
                ('background_image', models.ImageField(default=None, upload_to='department')),
                ('vision', models.TextField(default=None)),
                ('mission', models.TextField(default=None)),
                ('program_type', models.PositiveIntegerField(choices=[('Under Graduate', 'Under Graduate'), ('Post Graduate', 'Post Graduate')], default='Under Graduate')),
                ('brochure', models.FileField(blank=True, default=None, upload_to='department/brochure')),
                ('department_description', models.TextField(default=None)),
                ('best_moment1', models.ImageField(default=None, upload_to='department/best-moments')),
                ('best_moment2', models.ImageField(default=None, upload_to='department/best-moments')),
                ('best_moment3', models.ImageField(default=None, upload_to='department/best-moments')),
                ('best_moment4', models.ImageField(default=None, upload_to='department/best-moments')),
            ],
        ),
        migrations.CreateModel(
            name='Achieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.TextField(default=None, max_length=100)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.department')),
            ],
        ),
    ]
