# Generated by Django 3.1.7 on 2021-04-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_auto_20210404_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineapplication',
            name='biology1',
            field=models.CharField(default=None, max_length=20, verbose_name='Biology'),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='board1',
            field=models.CharField(default=None, max_length=10, verbose_name='    Board'),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='chemistry1',
            field=models.CharField(default=None, max_length=20, verbose_name='Chemistry'),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='current_city',
            field=models.CharField(default=None, max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='current_phone',
            field=models.CharField(default=None, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='current_pincode',
            field=models.CharField(default=None, max_length=15, verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='eligible_percentage1',
            field=models.CharField(default=None, max_length=20, verbose_name='Eligible Percentage'),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='english1',
            field=models.CharField(default=None, max_length=20, verbose_name='English'),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='language1',
            field=models.CharField(default=None, max_length=20, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='maths1',
            field=models.CharField(default=None, max_length=20, verbose_name=' Maths'),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='month_and_year_of_passing1',
            field=models.CharField(default=None, max_length=20, verbose_name='Month And Year of Passing'),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='name_of_institution1',
            field=models.CharField(default=None, max_length=100, verbose_name='Name of Institution'),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='percentage_of_marks1',
            field=models.CharField(default=None, max_length=3, verbose_name='Percentage of Marks'),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='permanent_city',
            field=models.CharField(default=None, max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='permanent_phone',
            field=models.CharField(default=None, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='permanent_pincode',
            field=models.CharField(default=None, max_length=15, verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='physics1',
            field=models.CharField(default=None, max_length=20, verbose_name='Physics'),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='reg_no',
            field=models.CharField(default=None, max_length=20, verbose_name='Registration number'),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='reg_no1',
            field=models.CharField(default=None, max_length=20, verbose_name='Registration number'),
        ),
    ]
