# Generated by Django 3.1.2 on 2020-11-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_achieve_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achieve',
            new_name='Achievement',
        ),
        migrations.RemoveField(
            model_name='department',
            name='best_moment1',
        ),
        migrations.RemoveField(
            model_name='department',
            name='best_moment2',
        ),
        migrations.RemoveField(
            model_name='department',
            name='best_moment3',
        ),
        migrations.RemoveField(
            model_name='department',
            name='best_moment4',
        ),
        migrations.CreateModel(
            name='best_moments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_moment', models.ImageField(default=None, upload_to='department/best-moments')),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.department')),
            ],
        ),
    ]
