# Generated by Django 3.1.2 on 2020-11-21 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0010_auto_20201121_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='best_moments',
            options={'verbose_name': 'Best Moment', 'verbose_name_plural': 'Best Moments'},
        ),
        migrations.AddField(
            model_name='department',
            name='duration',
            field=models.IntegerField(default=None, help_text='No of years'),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('Qualification_And_Specification', models.CharField(default=None, max_length=50)),
                ('AreaOfIntrest', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.IntegerField(default=None, max_length=2)),
                ('Phone', models.IntegerField(max_length=10)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.department')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
            },
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('image', models.ImageField(default=None, upload_to='department/HOD')),
                ('Qualification_And_Specification', models.CharField(default=None, max_length=50)),
                ('AreaOfIntrest', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField(max_length=10)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.department')),
            ],
            options={
                'verbose_name': 'Head of the department',
                'verbose_name_plural': 'Head of the department',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='department/gallery')),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.department')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('quantity', models.IntegerField(default=None)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.department')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
            },
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards', models.TextField(default=None, max_length=100)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.department')),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
            },
        ),
    ]
