# Generated by Django 3.1.2 on 2020-11-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_auto_20201121_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Facility', 'verbose_name_plural': 'Facilities'},
        ),
        migrations.AddField(
            model_name='hod',
            name='experience',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='program_type',
            field=models.PositiveIntegerField(choices=[(1, 'Under Graduate'), (2, 'Post Graduate')], default='1'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='experience',
            field=models.IntegerField(default=None),
        ),
    ]
