# Generated by Django 3.1.2 on 2020-11-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0012_auto_20201121_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievements'},
        ),
        migrations.AlterField(
            model_name='department',
            name='Name',
            field=models.PositiveIntegerField(choices=[(1, 'Physiology'), (2, 'Anatomy'), (3, 'Community Medicine'), (4, 'Tb & Chest Diseases'), (5, 'Paediatrics'), (6, 'Orthopaedics'), (7, 'Opthalmology'), (8, 'Psychiatry'), (9, 'Obstetrics & Gynaecology'), (10, 'General Surgery'), (11, 'Forensic Medicine'), (12, 'ENT'), (13, 'Dermatology'), (14, 'Dentistry'), (15, 'Anaesthesiology'), (16, 'Pharmacology'), (17, 'Bio Chemistry'), (18, 'Pathology'), (19, 'Micro Biology'), (20, 'Radio Diagnosis'), (21, 'General Medicine')], default='1'),
        ),
        migrations.AlterField(
            model_name='hod',
            name='Phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
