# Generated by Django 3.1.2 on 2021-02-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0013_auto_20201122_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.PositiveIntegerField(choices=[(1, 'Central Laboratory'), (2, 'Library'), (3, 'Infrastructure'), (4, 'Internet Facility'), (5, 'Seminar Hall'), (6, 'Canteen'), (7, 'Hostel and Quarters'), (8, 'Transport'), (9, 'Anti-ragging & Gender harassment')], default='1')),
                ('image', models.ImageField(default=None, upload_to='college/facility')),
                ('overview', models.TextField()),
            ],
            options={
                'verbose_name': 'facility',
                'verbose_name_plural': 'Facilities',
            },
        ),
    ]
