# Generated by Django 3.1.2 on 2021-02-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0014_main_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='best_moments',
            name='best_moment',
            field=models.ImageField(default=None, upload_to='college/department/best-moments'),
        ),
        migrations.AlterField(
            model_name='department',
            name='background_image',
            field=models.ImageField(default=None, upload_to='college/department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='brochure',
            field=models.FileField(blank=True, default=None, upload_to='college/department/brochure'),
        ),
        migrations.AlterField(
            model_name='event',
            name='brochure',
            field=models.FileField(blank=True, default=None, null=True, upload_to='college/events/brochure'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='college/events'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default=None, upload_to='college/department/gallery'),
        ),
        migrations.AlterField(
            model_name='hod',
            name='image',
            field=models.ImageField(default=None, upload_to='college/department/HOD'),
        ),
        migrations.AlterField(
            model_name='new',
            name='brochure',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='college/news/brochure'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='college/news'),
        ),
    ]
