# Generated by Django 3.1.7 on 2021-03-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0015_auto_20210225_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Select_Degree', models.PositiveIntegerField(choices=[(1, 'btech'), (2, 'mtech')], default='1')),
                ('image', models.ImageField(default=None, upload_to='college/admission')),
            ],
        ),
    ]
