# Generated by Django 3.1.7 on 2021-03-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0016_admission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='Select_Degree',
            new_name='degree',
        ),
        migrations.AddField(
            model_name='admission',
            name='branch',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='admission',
            name='course_type',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='admission',
            name='year',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
