# Generated by Django 3.1.7 on 2021-03-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0017_auto_20210329_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='degree',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
