# Generated by Django 3.1.7 on 2021-04-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0018_auto_20210329_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hyperlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=250)),
                ('hyperlink', models.URLField(max_length=250)),
            ],
        ),
    ]
