# Generated by Django 3.1.7 on 2021-04-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0020_hyperlink_facility_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=250)),
                ('author', models.CharField(default=None, max_length=150)),
                ('date', models.DateField()),
                ('pdf_file', models.FileField(upload_to='college/department/paper_publications')),
            ],
        ),
    ]
