# Generated by Django 3.1.7 on 2021-04-02 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0021_paperpublication'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperpublication',
            name='department_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='college.department'),
        ),
    ]
