# Generated by Django 3.1.7 on 2021-04-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0022_paperpublication_department_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EleventhDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(default=None, max_length=20)),
                ('month_and_year_of_passing', models.CharField(default=None, max_length=20)),
                ('percentage_of_marks', models.CharField(default=None, max_length=3)),
                ('board', models.CharField(default=None, max_length=10)),
                ('name_of_institution', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MarkDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default=None, max_length=20)),
                ('english', models.CharField(default=None, max_length=20)),
                ('maths', models.CharField(default=None, max_length=20)),
                ('physics', models.CharField(default=None, max_length=20)),
                ('chemistry', models.CharField(default=None, max_length=20)),
                ('biology', models.CharField(default=None, max_length=20)),
                ('eligible_percentage', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ParentsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currrent_address_line1', models.CharField(default=None, max_length=20)),
                ('current_address_line2', models.CharField(default=None, max_length=20)),
                ('current_city', models.CharField(default=None, max_length=30)),
                ('current_pincode', models.CharField(default=None, max_length=15)),
                ('current_phone', models.CharField(default=None, max_length=20)),
                ('permanent_address_line1', models.CharField(default=None, max_length=20)),
                ('permanent_address_line2', models.CharField(default=None, max_length=20)),
                ('permanent_city', models.CharField(default=None, max_length=30)),
                ('permanent_pincode', models.CharField(default=None, max_length=15)),
                ('permanent_phone', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ParentsInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(default=None, max_length=30)),
                ('father_occupation', models.CharField(default=None, max_length=50)),
                ('father_income', models.CharField(default=None, max_length=20)),
                ('mother_name', models.CharField(default=None, max_length=30)),
                ('mother_occupation', models.CharField(default=None, max_length=50)),
                ('mother_income', models.CharField(default=None, max_length=20)),
                ('gaurdian_name', models.CharField(default=None, max_length=30)),
                ('gaurdian_occupation', models.CharField(default=None, max_length=50)),
                ('gaurdian_income', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(default=None, max_length=50)),
                ('date_of_birth', models.CharField(default=None, max_length=20)),
                ('age', models.IntegerField(default=None)),
                ('blood_group', models.CharField(default=None, max_length=3)),
                ('mother_tounge', models.CharField(default=None, max_length=15)),
                ('religion', models.CharField(default=None, max_length=20)),
                ('cast', models.CharField(default=None, max_length=50)),
                ('community', models.CharField(default=None, max_length=20)),
                ('reserved_category', models.CharField(default=None, max_length=20)),
                ('physically_handicapped', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(default=None, max_length=20)),
                ('native_place', models.CharField(default=None, max_length=20)),
                ('state', models.CharField(default=None, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TcDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_no', models.CharField(default=None, max_length=20)),
                ('tc_date', models.CharField(default=None, max_length=20)),
                ('medium_of_instruction', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TwelthDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(default=None, max_length=20)),
                ('month_and_year_of_passing', models.CharField(default=None, max_length=20)),
                ('percentage_of_marks', models.CharField(default=None, max_length=3)),
                ('board', models.CharField(default=None, max_length=10)),
                ('name_of_institution', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
