# Generated by Django 3.1.7 on 2021-04-03 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0023_eleventhdetails_markdetails_parentsdetails_parentsinformation_personalinformation_studentdetails_tcd'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleventhdetails',
            name='admission_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='college.admission'),
        ),
        migrations.AddField(
            model_name='parentsdetails',
            name='admission_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='college.admission'),
        ),
        migrations.AddField(
            model_name='parentsinformation',
            name='admission_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='college.admission'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='admission_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='college.admission'),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='admission_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='college.admission'),
        ),
        migrations.AddField(
            model_name='tcdetails',
            name='admission_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='college.admission'),
        ),
        migrations.AddField(
            model_name='twelthdetails',
            name='admission_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='college.admission'),
        ),
    ]
