# Generated by Django 3.1.7 on 2021-04-03 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0024_auto_20210403_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdetails',
            name='some_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='college.eleventhdetails'),
        ),
    ]
