# Generated by Django 3.1.7 on 2021-04-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0026_markdetails_another_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_enquired', models.BooleanField()),
            ],
        ),
    ]
