# Generated by Django 3.1.7 on 2021-04-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0028_enquirystatus_admission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='physically_handicapped',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
