# Generated by Django 3.1.2 on 2020-11-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0003_auto_20201116_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_event',
            name='image',
            field=models.ImageField(default=None, upload_to='main-events'),
        ),
    ]
