# Generated by Django 3.1.7 on 2021-04-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0006_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='mci_subcatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=250)),
                ('document_pdf', models.FileField(default=None, upload_to='mci')),
                ('href', models.URLField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='mci',
            name='href',
            field=models.URLField(default=None),
        ),
    ]
