# Generated by Django 3.1.7 on 2021-04-22 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0007_auto_20210422_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='mci_subcatagory',
            name='MCI_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MainPage.mci'),
        ),
    ]
