# Generated by Django 3.1.2 on 2020-11-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='indexvideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_Title', models.CharField(default=None, max_length=500)),
                ('Video_Description', models.TextField(default=None, max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='hospital/videos', verbose_name='video')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default=None, upload_to='events'),
        ),
    ]
