# Generated by Django 3.1.2 on 2020-11-28 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Hospital Gallery', 'verbose_name_plural': 'Hospital Gallery'},
        ),
    ]
