# Generated by Django 3.1.2 on 2021-02-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_gallery_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.PositiveIntegerField(choices=[(1, 'Anaesthesiology'), (2, 'Dentistry'), (3, 'Dermatology'), (4, 'ENT'), (5, 'General Medical'), (6, 'General Surgery'), (7, 'OBG'), (8, 'Ophthalmology'), (9, 'Orthopaedics'), (10, 'Pardiatrics'), (11, 'Physiotherapy'), (12, 'Psychiatry'), (13, 'Radio Diagnosis'), (14, 'Pulmonology')], default='1')),
                ('image', models.ImageField(blank=True, default=None, upload_to='hospital/clinical')),
                ('overview', models.TextField()),
            ],
            options={
                'verbose_name': 'Clinical',
                'verbose_name_plural': 'Clinical',
            },
        ),
        migrations.CreateModel(
            name='Main_facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.PositiveIntegerField(choices=[(1, '24*7 Service'), (2, 'Ambulance'), (3, 'Blood Bank'), (4, "covid'19"), (5, 'ICU'), (6, 'IP & OP Service'), (7, 'Pharmacy')], default='1')),
                ('image', models.ImageField(blank=True, default=None, upload_to='hospital/facilities')),
                ('overview', models.TextField()),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='Sspeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.PositiveIntegerField(choices=[(1, 'Cardiology'), (2, 'Gastroenterology'), (3, 'Nephrology'), (4, 'Plastic Surgery'), (5, 'Paediatric Surgery'), (6, 'Surgical Gastroenterology'), (7, 'Surgical Onocology'), (8, 'Urology'), (9, 'Vascular Surgery')], default='1')),
                ('image', models.ImageField(blank=True, default=None, upload_to='hospital/super-speciality')),
                ('overview', models.TextField()),
            ],
            options={
                'verbose_name': 'Super Speciality',
                'verbose_name_plural': 'Super Specialities',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='brochure',
            field=models.FileField(blank=True, default=None, null=True, upload_to='hospital/events/brochure'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default=None, upload_to='hospital/events'),
        ),
        migrations.AlterField(
            model_name='new',
            name='brochure',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='hospital/news/brochure'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='hospital/news'),
        ),
    ]
