# Generated by Django 3.1.7 on 2021-03-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_auto_20210225_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexvideo',
            options={'verbose_name': 'Home page video update', 'verbose_name_plural': 'Home page video update'},
        ),
        migrations.AlterField(
            model_name='clinical',
            name='Name',
            field=models.PositiveIntegerField(choices=[(1, 'Anaesthesiology'), (2, 'Dentistry'), (3, 'Dermatology'), (4, 'ENT'), (5, 'General Medicine'), (6, 'General Surgery'), (7, 'OBG'), (8, 'Ophthalmology'), (9, 'Orthopaedics'), (10, 'Paediatrics'), (11, 'Physiotherapy'), (12, 'Psychiatry'), (13, 'Radio Diagnosis'), (14, 'Pulmonology')], default='1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='hospital/events'),
        ),
        migrations.AlterField(
            model_name='sspeciality',
            name='Name',
            field=models.PositiveIntegerField(choices=[(1, 'Cardiology'), (2, 'Gastroenterology'), (3, 'Nephrology'), (4, 'Plastic Surgery'), (5, 'Paediatric Surgery'), (6, 'Surgical Gastroenterology'), (7, 'Surgical Onocology'), (8, 'Urology'), (9, 'Vascular Surgery'), (10, 'neurology')], default='1'),
        ),
    ]
